In [2]:
import numpy as np 

## Lets create a 1D Array

In [4]:
arr_1d = np.array([1,2,3,4,5])

print(arr_1d)

[1 2 3 4 5]


## Lets Create a 2D Array

In [5]:
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


## Lets Create 3D Array 

In [6]:
arr_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
# To check diemention of array

print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

1
2
3


## To find shape of array

In [8]:
print("Shape of 2D Array : " + str(arr_1d.shape) + "  ( Which means it is 1d array with 5 elements)")  
print("Shape of 2D Array : "+ str(arr_2d.shape) + "   ( Which means it is 2D Array   2 row and 3 column)")

Shape of 2D Array : (5,)  ( Which means it is 1d array with 5 elements)
Shape of 2D Array : (2, 3)   ( Which means it is 2D Array   2 row and 3 column)


In [9]:
print(arr_2d.size)          # To find total numbe of elements in a array
print(arr_2d.dtype)       # to find data type

6
int32


## Reshape an array

In [10]:
# 1D array into 2D Array

arr_r = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new_arr = arr_r.reshape(4,3)

print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
# 1D Array into 3D Array 
arr_r = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

new_arr = arr_r.reshape(2,2,3)    # nof of bloack   # no of row  # now of column
print(new_arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [12]:
# Converting any diemention array into 1D

arr = np.array([[[1,2],[3,4],[5,6],[7,8]]])      
print("Orginal Array D : ",arr.ndim)

new = arr.reshape(-1)
print(new)
print("reshaped D is : ",new.ndim)

Orginal Array D :  3
[1 2 3 4 5 6 7 8]
reshaped D is :  1


 ## Generate Array 

In [13]:
zero_array = np.zeros((2,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
one_array = np.ones((2,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arr_range = np.arange(0,10,2)
print(arr_range)

[0 2 4 6 8]


In [16]:
arr_random = np.random.rand(2,2)
print(arr_random)                         # randomly create from 0 to 1

[[0.59579075 0.09052688]
 [0.32411851 0.99067219]]


In [17]:
arr_random_int = np.random.randint(1,5,size=(2,3))            # create randome 1 to 5 
print(arr_random_int)

[[1 4 3]
 [1 4 2]]


# To create a  n dimention array     

In [18]:
arr_5d = np.array([1,2,3],ndmin=5)
print(arr_5d)
print("Dimention is : ",arr_5d.ndim)

[[[[[1 2 3]]]]]
Dimention is :  5


## Basic Operations using Numpy 

In [19]:
# ELement wise Operations

arr = np.array([1,2,3])

print(arr + 10)         # each element add by 10

[11 12 13]


In [20]:
# MAtrix Multiplication 

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

res = np.dot(a,b)
print(res)

[[19 22]
 [43 50]]


## Diference between copy and View 

In [21]:
# copy is a new array          


arr_c = np.array([1,2,3,4,5])
x = arr.copy()
arr_c[0] = 456

print(arr_c)
print(x)

[456   2   3   4   5]
[1 2 3]


In [22]:
 # and view is just view of orginal array

arr_v = np.array([1,2,3,4,5])
x = arr_v.view()
arr_v[0] = 101010

print(arr_v)
print(x)                         # both will change

[101010      2      3      4      5]
[101010      2      3      4      5]


In [23]:
# Iterating a numpy array

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr.flat:            #normaly using 3 loop also we can do or use flat or nditer    for x in np.nditer(arr)           
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


## ARRAY JOINING

In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

narr = np.concatenate((arr1,arr2))
print(narr)

[1 2 3 4 5 6]


In [25]:
arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[5,6],[7,8]])

n1arr = np.concatenate((arr3,arr4))
print(n1arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## We can SPlit Arrays 

In [26]:
aa = np.array([1,2,3,4,5])

sp = np.array_split(aa,3)
print(sp)


[array([1, 2]), array([3, 4]), array([5])]


## Array Searching

In [27]:
sr = np.array([1,2,3,4,5])

x = np.where(sr==3)

print("find on index : ",x)

find on index :  (array([2], dtype=int64),)


In [28]:
# To find even number index

evn = np.where(sr % 2 ==0)
print(evn)

(array([1, 3], dtype=int64),)


In [29]:
# TO Perfrom Binary Search  in array  use --> searchsorted()

arr = np.array([6, 7, 8, 9])

kl = np.searchsorted(arr,8)
print(kl)

2


### Array Sorting

In [30]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

n = np.sort(arr)
print(n)

[[2 3 4]
 [0 1 5]]


## Statical Operations using Numpy 

In [32]:
ap = np.array([1,2,3,4,5,6])

print("Mean of the array :",np.mean(ap))
print("Median of the array :",np.median(ap))
print("Sum of the array :",np.sum(ap))
print("STD of the array :",np.std(ap))
print("Varience of the array :",np.var(ap))

Mean of the array : 3.5
Median of the array : 3.5
Sum of the array : 21
STD of the array : 1.707825127659933
Varience of the array : 2.9166666666666665


In [44]:
# A practical question

array = np.random.randint(1,12,size=(3,3))
print(array)
print(np.min(array))
print(np.max(array))
print(np.sum(array))

[[ 5  6  2]
 [ 8  7  4]
 [ 1  7 11]]
1
11
51
