# Numpy Tutorial 

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [3]:
print(arr * 2)

[2 4 6 8]


In [6]:
print(arr[:2])

[1 2]


In [9]:
re = arr.reshape(2,2)
print(re)
print(re.ndim)

[[1 2]
 [3 4]]
2


In [19]:
z = np.zeros((2,2,2))
print(z)
print(z.ndim)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
3


In [20]:
o = np.ones((2,2))
print(o)

[[1. 1.]
 [1. 1.]]


In [37]:
arange = np.arange(1,7).reshape(2,3)
print(arange)

[[1 2 3]
 [4 5 6]]


In [38]:
a = np.eye(2)
print(a)

[[1. 0.]
 [0. 1.]]


In [44]:
random_arr = np.random.rand(10).reshape(2,5)
print(random_arr)

[[0.48535848 0.46389925 0.58036192 0.90328647 0.30803388]
 [0.28694619 0.94203578 0.93341796 0.08966464 0.390938  ]]


In [45]:
arr = np.array([12, 34, 5, 67, 8, 1])

print("Min of array : ",np.max(arr))
print("Min of array : ",np.min(arr))

Min of array :  67
Min of array :  1


In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("Mean : ",np.mean(arr))
print("Median : ",np.median(arr))
print("STD  is ",np.std(arr))
print("Varience : ",np.var(arr))

Mean :  5.0
Median :  5.0
STD  is  2.581988897471611
Varience :  6.666666666666667


In [50]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Sum of 2D array : ",np.sum(arr_2d))

Sum of 2D array :  45


In [51]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

vertical_stack = np.vstack((arr1, arr2))
horizontal_stack = np.hstack((arr1, arr2))

print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]


In [54]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

sp = np.array_split(arr_2d,2)
print(sp)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


In [56]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

even = np.where(arr_2d %2 == 0)
print(arr_2d[even])

[2 4 6 8]


In [60]:
arr_2d.dtype

dtype('int32')

# PANDAS TUTORIAL

In [2]:
import pandas as  pd

In [3]:
data = {'A': [10,20,30],'B':[40,50,60]}
df = pd.DataFrame(data,index=['x','y','z'])

print(df.loc['x','B'])

40


In [4]:
data = [10,20,30,40,50]

series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [5]:
data2 = {
    'Name': ['Alan','shan','kiran'],
    'Age' : [17,19,22],
    'City': ['KZD','KSD','TVM']
}

df = pd.DataFrame(data2)
print(df)

    Name  Age City
0   Alan   17  KZD
1   shan   19  KSD
2  kiran   22  TVM


In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None


In [7]:
print(df.describe())

             Age
count   3.000000
mean   19.333333
std     2.516611
min    17.000000
25%    18.000000
50%    19.000000
75%    20.500000
max    22.000000


In [8]:
print(df['Name'])

0     Alan
1     shan
2    kiran
Name: Name, dtype: object


In [9]:
print(df[['Name','City']])

    Name City
0   Alan  KZD
1   shan  KSD
2  kiran  TVM


In [10]:
df['Income'] = [20000,49800,35499]

In [11]:
df

Name  Age City  Income
0   Alan   17  KZD   20000
1   shan   19  KSD   49800
2  kiran   22  TVM   35499

In [12]:
fil = df[df['Age'] > 19]
print(fil)

    Name  Age City  Income
2  kiran   22  TVM   35499


In [13]:
sort = df.sort_values(by='Age',ascending=False)
print(sort)

    Name  Age City  Income
2  kiran   22  TVM   35499
1   shan   19  KSD   49800
0   Alan   17  KZD   20000


In [14]:
import pandas as pd
import numpy as np

# Creating a DataFrame with 30 entries and some missing values
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Henry', 'Ivy', 'Jack',
             'Kathy', 'Leo', 'Mona', 'Nina', 'Oscar', 'Paul', 'Quincy', 'Rachel', 'Sam', 'Tina',
             'Uma', 'Vince', 'Wendy', 'Xander', 'Yara', 'Zack', 'Annie', 'Brian', 'Cathy', 'Derek'],
    'Age': [25, 30, np.nan, 40, 22, np.nan, 34, 45, 27, 33, 29, 31, 26, np.nan, 44, 38, 37, 28, np.nan, 23,
            32, 39, np.nan, 41, 24, 35, 36, np.nan, 42, 29],
    'Salary': [50000, np.nan, 54000, 58000, 52000, 56000, np.nan, 60000, 55000, 57000, np.nan, 53000, 51000, 59000, 
               np.nan, 62000, 64000, 65000, 63000, np.nan, 52000, np.nan, 68000, 66000, 67000, 69000, 71000, np.nan, 72000, 73000]
}

df = pd.DataFrame(data)
df.head(5)


Name   Age   Salary
0    Alice  25.0  50000.0
1      Bob  30.0      NaN
2  Charlie   NaN  54000.0
3    David  40.0  58000.0
4      Eva  22.0  52000.0

In [15]:
df.isnull().sum()

Name      0
Age       6
Salary    7
dtype: int64

In [16]:
df.fillna(value=0,inplace=True)

In [17]:
df.isnull().sum()

Name      0
Age       0
Salary    0
dtype: int64

In [18]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

### Merging and Joining DataFRames 

In [21]:
d1 = {
    'ID': [1,2],
    'Name' : ['janu','ruku']
}

d2 = {
    'ID': [3,4],
    'Name': ['Ramesh','Satheesh ']
}


df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

merge = pd.concat([df1,df2],ignore_index=True)

merge.head()

ID       Name
0   1       janu
1   2       ruku
2   3     Ramesh
3   4  Satheesh

#### Joining DataFrame 

In [23]:
df1 = pd.DataFrame({'ID':[1,2],'Name':['Ashok','Ariya']})
df2 = pd.DataFrame({'ID':[2,1],'Age':[30,25]})

merge = pd.merge(df1,df2,on='ID')
merge.head()

ID   Name  Age
0   1  Ashok   25
1   2  Ariya   30

## SCKIT LEARN 