Concepts of Matrix
Matrix representations, transformation
Dot Product
Eigenvalues
Eigenvectors etc.
Matrix Operations
Matrix types


In [10]:
m1 = [
    
    [1,2,3],
    [4,5,6]
]

m2 = [
    [10,20,30],
    [40,50,60]
]

res = []
for i in range(len(m1)):
    row = []
    for j in range(len(m1[0])):
        row.append(m1[i][j] + m2[i][j])
    res.append(row)
    
print(res)
        
    

[[11, 22, 33], [44, 55, 66]]


With using numpy

In [12]:
import numpy  as np

m1 = np.array([[1,2,3],[4,5,6]])
m2 = np.array([[10,20,30],[40,50,60]])

res = m1 + m2

print(res)

[[11 22 33]
 [44 55 66]]


In [17]:
# Scalar multiplication 

m = [[21,23,21],[3,2,12]]

print("Orginal matrix : ",m)

res = []
for i in range(len(m)):
    row = []
    for j in range(len(m[0])):
        row.append(m[i][j] * 3)
    res.append(row)
    
print("Scalar multiple of 3 is : ",res)

Orginal matrix :  [[21, 23, 21], [3, 2, 12]]
Scalar multiple of 3 is :  [[63, 69, 63], [9, 6, 36]]


In [22]:
# Transpose matrix 

m = [
    [11,12,13],
    [14,15,16]
]


t = []

for j in range(len(m[0])):
    row = []
    for i in range(len(m)):
        row.append(m[i][j])
    t.append(row)
    
print("Orginal matrix : ",m)
print("Transpose matrix :",t)

Orginal matrix :  [[11, 12, 13], [14, 15, 16]]
Transpose matrix : [[11, 14], [12, 15], [13, 16]]


In [25]:
# Determinant

mat_2x2 = [
    [1,2],
    [3,4]
]


mat_3x3 = [
    [1,2,3],
    [4,5,6],
    [6,7,8]
]

def det_2(mat):
    a,b = mat[0]
    c,d = mat[1]
    
    return (a*d) - (b*c)

print("Determinant of 2x2 matrix is : ",det_2(mat_2x2))

def det_3(mat):
    a,b,c = mat[0]
    d,e,f = mat[1]
    g,h,i = mat[2]
    
    return (a * (e * i - f * h) - b * (d*i - f*g) + c * (d*h - e *g))

print("Determinant of 3x3 matrix is : ",det_3(mat_3x3))


    

Determinant of 2x2 matrix is :  -2
Determinant of 3x3 matrix is :  0


# Inverse

In [31]:
mat_b = [
    [2,3],
    [4,5]
    ]  
    
    
def inverse(m):
    a,b = m[0]
    c,d = m[1]
    
    det = (a * d) - (b * c)
    
    if det == 0:
        return "Cant inverse beacuse det is 0"
    inver = [
        [d/det,-b/det],
        [-c/det,a/det]
    ]
    
    return inver

print(inverse(mat_b))

[[-2.5, 1.5], [2.0, -1.0]]


In [34]:
# Determint of 3x3 matrix using     numpy 

import numpy as np
mat_3 = A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

det_A = np.linalg.det(mat_3)

if det_A ==0:
    print("det is zero ")

inv = np.linalg.inv(mat_3)
print("Inverse is :",inv)

Inverse is : [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


# Dot Products 

In [38]:
a = [2,3,4]
b = [1,0,-1]

def dot(a,b):
    dot_pro = 0
    for i in range(len(a)):
        dot_pro += a[i] * b[i]
        
    return dot_pro

print(dot(a,b))
    

-2


In [39]:
import numpy as np  # using dot prodcut 

dot = np.dot(a,b)
print(dot)

-2


In [44]:
# Magnitude of a vector
a = [2,-3,6]
sq = [x **2 for x in a ]
sum_sq = sum(sq)
mag = sum_sq ** 0.5
print(mag)


7.0
